#!/bin/bash
ENV_NAME=${ENV_NAME:-"paper"}

. $ENV_NAME.env
if [ "$BROKER" == "td" ]; then
    ENV_FILE=$ENV_NAME.env ./run.sh refresh-tokens
fi

module=`echo $1 | sed "s@/@.@g" | sed "s@.py@@g"`
echo $module

nodemon -e py -x "python3 -c 'from $module import main; main()'"
