#!/bin/bash

ENV_NAME=${ENV_NAME:-"paper"}

function dev_source_env() {
    ENV_NAME=${ENV_NAME:-"paper"}
    if [[ ! -f $ENV_NAME.env ]]; then
        echo "Could not find $ENV_NAME.env, exiting"
        exit 1
    fi
    cat $ENV_NAME.env | sed "s/..*/export &/" > active.dev.env
    source active.dev.env
}

dev_source_env
nodemon -e py -x "python3 -c 'import src.log; from src.scan.$1 import prepare_csv; prepare_csv()'"
